version: '3.9'
services:
  db:
    image: oscarfonts/h2:2.1.214
    command: oscarfonts/h2d --default-authentication-plugin=mysql_native_passwor
    restart: always
    environment:
      TZ: America/Sao_Paulo
      H2_ROOT_PASSWORD: admin123
      H2_USER: docker
      H2_PASSWORD: admin123
      H2_DATABASE: mercearia_auto_atendimento_db
      H2_ROOT_HOST: '%'
      H2_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      -auto-atendimento-network
  auto-atendimento:
    image: jumarket/auto-atendimento
    restart: always
    build: ./auto-atendimento
    working_dir: /auto-atendimento
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:h2:mem:db
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
       - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      -auto-atendimento-network
networks:
  auto-atendimento-network:
    driver: bridge