spring:
  datasource:
    url: jdbc:h2:mem:mercearia_auto_atendimento_db
    username: jumarket
    password:
  jpa:
    show-sql: true
    hibernate:
     # ddl-auto: none
    properties:
        hibernate.format_sql: true
  server:
    port: 80
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
